language: ruby
rvm:
  - 2.1.3
code_climate:
  repo_token:
    secure: BffTkuz+BgginYvK2MsIyo522eL97GXcv/bOde0Dd8rBZODFl81LV6Sc5iuQBxT8NKwUMG5a3YRULpcspScim6WVDYQw4YeqtRs+pGnXTFe40XFnkBGatWUgksNLdZhaPOJDo09e7Sh4SOSyrqkRuWcw5JZGf8o8tiqJRBAZ9cU=
